trigger:
- main

pool:
  name: Default

steps:

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'maven-feed'

- task: Maven@3
  displayName: Build and Deploy WAR
  inputs:
    mavenPOMFile: 'pom.xml'
    goals: 'clean deploy'
    options: '-DskipTests'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\jdk8'